export enum Direction {
  NORTH = 'Põhi',
  SOUTH = 'Lõuna',
  EAST = 'Ida',
  WEST = 'Lääs',
  NORTHEAST = 'Kirre',
  SOUTHEAST = 'Kagu',
  SOUTHWEST = 'Edel',
  NORTHWEST = 'Loe',
  CENTER = 'Keskel'
}

export type DirectionSetType = 'compass' | 'simple' | 'adventure' | 'regions' | 'family' | 'solar' | 'body' | 'weather' | 'emotions' | 'time' | 'elements' | 'chess';

export const DIRECTION_SETS: Record<DirectionSetType, Record<string, { r: number; c: number }>> = {
  compass: {
    'loe': { r: 0, c: 0 },
    'põhi': { r: 0, c: 1 },
    'kirre': { r: 0, c: 2 },
    'lääs': { r: 1, c: 0 },
    'keskel': { r: 1, c: 1 },
    'ida': { r: 1, c: 2 },
    'edel': { r: 2, c: 0 },
    'lõuna': { r: 2, c: 1 },
    'kagu': { r: 2, c: 2 },
  },
  simple: {
    'ülal-vasakul': { r: 0, c: 0 },
    'ülal': { r: 0, c: 1 },
    'ülal-paremal': { r: 0, c: 2 },
    'vasakul': { r: 1, c: 0 },
    'keskel': { r: 1, c: 1 },
    'paremal': { r: 1, c: 2 },
    'all-vasakul': { r: 2, c: 0 },
    'all': { r: 2, c: 1 },
    'all-paremal': { r: 2, c: 2 },
  },
  adventure: {
    'loss': { r: 0, c: 0 },
    'mets': { r: 0, c: 1 },
    'järv': { r: 0, c: 2 },
    'koobas': { r: 1, c: 0 },
    'kodu': { r: 1, c: 1 },
    'küla': { r: 1, c: 2 },
    'mägi': { r: 2, c: 0 },
    'põld': { r: 2, c: 1 },
    'jõgi': { r: 2, c: 2 },
  },
  regions: {
    'harjumaa': { r: 0, c: 0 },
    'lääne-virumaa': { r: 0, c: 1 },
    'ida-virumaa': { r: 0, c: 2 },
    'läänemaa': { r: 1, c: 0 },
    'järvamaa': { r: 1, c: 1 },
    'tartumaa': { r: 1, c: 2 },
    'pärnumaa': { r: 2, c: 0 },
    'viljandimaa': { r: 2, c: 1 },
    'võrumaa': { r: 2, c: 2 },
  },
  family: {
    'ema': { r: 0, c: 0 },
    'isa': { r: 0, c: 1 },
    'tädi': { r: 0, c: 2 },
    'vend': { r: 1, c: 0 },
    'mina': { r: 1, c: 1 },
    'õde': { r: 1, c: 2 },
    'poeg': { r: 2, c: 0 },
    'tütar': { r: 2, c: 1 },
    'lapselaps': { r: 2, c: 2 },
  },
  solar: {
    'merkuur': { r: 0, c: 0 },
    'veenus': { r: 0, c: 1 },
    'maa': { r: 0, c: 2 },
    'marss': { r: 1, c: 0 },
    'päike': { r: 1, c: 1 },
    'jupiter': { r: 1, c: 2 },
    'saturn': { r: 2, c: 0 },
    'uraan': { r: 2, c: 1 },
    'neptuun': { r: 2, c: 2 },
  },
  body: {
    'silmad': { r: 0, c: 0 },
    'pea': { r: 0, c: 1 },
    'kõrvad': { r: 0, c: 2 },
    'vasak-käsi': { r: 1, c: 0 },
    'süda': { r: 1, c: 1 },
    'parem-käsi': { r: 1, c: 2 },
    'vasak-jalg': { r: 2, c: 0 },
    'kõht': { r: 2, c: 1 },
    'parem-jalg': { r: 2, c: 2 },
  },
  weather: {
    'torm': { r: 0, c: 0 },
    'vihm': { r: 0, c: 1 },
    'lumi': { r: 0, c: 2 },
    'tuul': { r: 1, c: 0 },
    'päike': { r: 1, c: 1 },
    'pilv': { r: 1, c: 2 },
    'udu': { r: 2, c: 0 },
    'vikerkaar': { r: 2, c: 1 },
    'välk': { r: 2, c: 2 },
  },
  emotions: {
    'viha': { r: 0, c: 0 },
    'kurbus': { r: 0, c: 1 },
    'hirm': { r: 0, c: 2 },
    'igavus': { r: 1, c: 0 },
    'õnn': { r: 1, c: 1 },
    'põnevus': { r: 1, c: 2 },
    'segadus': { r: 2, c: 0 },
    'rahu': { r: 2, c: 1 },
    'üllatus': { r: 2, c: 2 },
  },
  time: {
    'minevik': { r: 0, c: 0 },
    'olevik': { r: 0, c: 1 },
    'tulevik': { r: 0, c: 2 },
    'eile': { r: 1, c: 0 },
    'täna': { r: 1, c: 1 },
    'homme': { r: 1, c: 2 },
    'hommik': { r: 2, c: 0 },
    'keskpäev': { r: 2, c: 1 },
    'õhtu': { r: 2, c: 2 },
  },
  elements: {
    'jää': { r: 0, c: 0 },
    'õhk': { r: 0, c: 1 },
    'valgus': { r: 0, c: 2 },
    'vesi': { r: 1, c: 0 },
    'vaim': { r: 1, c: 1 },
    'tuli': { r: 1, c: 2 },
    'metall': { r: 2, c: 0 },
    'maa': { r: 2, c: 1 },
    'puit': { r: 2, c: 2 },
  },
  chess: {
    'vanker': { r: 0, c: 0 },
    'ratsu': { r: 0, c: 1 },
    'oda': { r: 0, c: 2 },
    'lipp': { r: 1, c: 0 },
    'kuningas': { r: 1, c: 1 },
    'ettur': { r: 1, c: 2 },
    'valge': { r: 2, c: 0 },
    'laud': { r: 2, c: 1 },
    'must': { r: 2, c: 2 },
  }
};

export const DIRECTIONS_MAP = DIRECTION_SETS.compass;

export interface ItemInfo {
  eesti: string;
  english: string;
  vene: string;
  hex?: string;
  icon?: string;
  image?: string;
}

export const COLORS: ItemInfo[] = [
  { eesti: 'Valge', english: 'White', vene: 'Белый', hex: '#FFFFFF' },
  { eesti: 'Must', english: 'Black', vene: 'Черный', hex: '#000000' },
  { eesti: 'Punane', english: 'Red', vene: 'Красный', hex: '#FF0000' },
  { eesti: 'Tumepunane', english: 'Dark Red', vene: 'Темно-красный', hex: '#8B0000' },
  { eesti: 'Helepunane', english: 'Light Red', vene: 'Светло-красный', hex: '#FF4D4D' },
  { eesti: 'Sinine', english: 'Blue', vene: 'Синий', hex: '#0000FF' },
  { eesti: 'Tumesinine', english: 'Dark Blue', vene: 'Темно-синий', hex: '#00008B' },
  { eesti: 'Helesinine', english: 'Light Blue', vene: 'Голубой', hex: '#ADD8E6' },
  { eesti: 'Kollane', english: 'Yellow', vene: 'Желтый', hex: '#FFFF00' },
  { eesti: 'Roheline', english: 'Green', vene: 'Зеленый', hex: '#00FF00' },
  { eesti: 'Tumeroheline', english: 'Dark Green', vene: 'Темно-зеленый', hex: '#006400' },
  { eesti: 'Heleroheline', english: 'Light Green', vene: 'Салатовый', hex: '#90EE90' },
  { eesti: 'Pruun', english: 'Brown', vene: 'Коричневый', hex: '#8B4513' },
  { eesti: 'Hall', english: 'Grey', vene: 'Серый', hex: '#808080' },
  { eesti: 'Roosa', english: 'Pink', vene: 'Розовый', hex: '#FF007F' },
  { eesti: 'Lilla', english: 'Purple', vene: 'Фиолетовый', hex: '#9400D3' },
  { eesti: 'Oranž', english: 'Orange', vene: 'Оранжевый', hex: '#FF8C00' },
  { eesti: 'Beež', english: 'Beige', vene: 'Бежевый', hex: '#F5F5DC' },
];

export const IPHONE_COLORS: ItemInfo[] = [
  { eesti: 'Must titaan', english: 'Black Titanium', vene: 'Черный титан', hex: '#444444', icon: 'Smartphone' },
  { eesti: 'Valge titaan', english: 'White Titanium', vene: 'Белый титан', hex: '#F5F5F0', icon: 'Smartphone' },
  { eesti: 'Naturaalne titaan', english: 'Natural Titanium', vene: 'Натуральный титан', hex: '#BEBDB8', icon: 'Smartphone' },
  { eesti: 'Kõrbetitaan', english: 'Desert Titanium', vene: 'Пустынный титан', hex: '#D4BFA6', icon: 'Smartphone' },
  { eesti: 'Südaöömust', english: 'Midnight', vene: 'Полночь', hex: '#191970', icon: 'Smartphone' },
  { eesti: 'Tähevalgus', english: 'Starlight', vene: 'Звездный свет', hex: '#FAF9F6', icon: 'Smartphone' },
  { eesti: 'Kosmosehall', english: 'Space Gray', vene: 'Космический серый', hex: '#535353', icon: 'Smartphone' },
  { eesti: 'Alpiroheline', english: 'Alpine Green', vene: 'Альпийский зеленый', hex: '#507672', icon: 'Smartphone' },
  { eesti: 'Sügavlilla', english: 'Deep Purple', vene: 'Глубокий фиолетовый', hex: '#594F63', icon: 'Smartphone' },
];

export const ANIMALS: ItemInfo[] = [
  { eesti: 'Hunt', english: 'Wolf', vene: 'Волк', icon: 'Wolf', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Eurasian_wolf_2.jpg/500px-Eurasian_wolf_2.jpg' },
  { eesti: 'Karu', english: 'Bear', vene: 'Медведь', icon: 'PawPrint', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Ours_brun_parcanimalierpyrenees_1.jpg/500px-Ours_brun_parcanimalierpyrenees_1.jpg' },
  { eesti: 'Rebane', english: 'Fox', vene: 'Лиса', icon: 'Fox', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg/500px-Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg' },
  { eesti: 'Jänes', english: 'Rabbit', vene: 'Заяц', icon: 'Rabbit', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Oryctolagus_cuniculus_Rcdo.jpg/500px-Oryctolagus_cuniculus_Rcdo.jpg' },
  { eesti: 'Orav', english: 'Squirrel', vene: 'Белка', icon: 'Squirrel', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Sciurus_vulgaris_1_%28Martin_Mecnarowski%29.jpg/500px-Sciurus_vulgaris_1_%28Martin_Mecnarowski%29.jpg' },
  { eesti: 'Siil', english: 'Hedgehog', vene: 'Еж', icon: 'Hedgehog', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Igel.JPG/500px-Igel.JPG' },
  { eesti: 'Hirv', english: 'Deer', vene: 'Олень', icon: 'Deer', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Red_Deer_Stag_%28Cervus_elaphus%29.jpg/500px-Red_Deer_Stag_%28Cervus_elaphus%29.jpg' },
  { eesti: 'Põder', english: 'Moose', vene: 'Лось', icon: 'Moose', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Alaska_moose.jpg/500px-Alaska_moose.jpg' },
  { eesti: 'Mäger', english: 'Badger', vene: 'Барсук', icon: 'PawPrint', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/M%C3%A4yr%C3%A4_%C3%84ht%C3%A4ri_4.jpg/500px-M%C3%A4yr%C3%A4_%C3%84ht%C3%A4ri_4.jpg' },
];

export const FRUITS: ItemInfo[] = [
  { eesti: 'Õun', english: 'Apple', vene: 'Яблоко', icon: 'Apple', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/500px-Pink_lady_and_cross_section.jpg' },
  { eesti: 'Pirn', english: 'Pear', vene: 'Груша', icon: 'Pear', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Pears.jpg/500px-Pears.jpg' },
  { eesti: 'Banaan', english: 'Banana', vene: 'Банан', icon: 'Banana', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/500px-Banana-Single.jpg' },
  { eesti: 'Maasikas', english: 'Strawberry', vene: 'Клубника', icon: 'Cherry', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/500px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg' },
  { eesti: 'Mustikas', english: 'Blueberry', vene: 'Черника', icon: 'Blueberry', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Blueberries.jpg/500px-Blueberries.jpg' },
  { eesti: 'Vaarikas', english: 'Raspberry', vene: 'Малина', icon: 'Heart', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Raspberry_-_halved_%28Rubus_idaeus%29.jpg/500px-Raspberry_-_halved_%28Rubus_idaeus%29.jpg' },
  { eesti: 'Kirss', english: 'Cherry', vene: 'Вишня', icon: 'Cherry', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cherry_season_%2848216568227%29.jpg/500px-Cherry_season_%2848216568227%29.jpg' },
  { eesti: 'Ploom', english: 'Plum', vene: 'Слива', icon: 'Plum', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Plums_African_Rose_-_whole%2C_halved_and_slice.jpg/500px-Plums_African_Rose_-_whole%2C_halved_and_slice.jpg' },
  { eesti: 'Viinamari', english: 'Grape', vene: 'Виноград', icon: 'Grape', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Grapes%2C_Rostov-on-Don%2C_Russia.jpg/500px-Grapes%2C_Rostov-on-Don%2C_Russia.jpg' },
];

export const VEGETABLES: ItemInfo[] = [
  { eesti: 'Porgand', english: 'Carrot', vene: 'Морковь', icon: 'Carrot', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/500px-Vegetable-Carrot-Bundle-wStalks.jpg' },
  { eesti: 'Kartul', english: 'Potato', vene: 'Картофель', icon: 'Potato', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Patates.jpg/500px-Patates.jpg' },
  { eesti: 'Kapsas', english: 'Cabbage', vene: 'Капуста', icon: 'Cabbage', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Cabbage_and_cross_section_on_white.jpg/500px-Cabbage_and_cross_section_on_white.jpg' },
  { eesti: 'Kurk', english: 'Cucumber', vene: 'Огурец', icon: 'Cucumber', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/500px-ARS_cucumber.jpg' },
  { eesti: 'Tomat', english: 'Tomato', vene: 'Помидор', icon: 'Tomato', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/500px-Tomato_je.jpg' },
  { eesti: 'Sibul', english: 'Onion', vene: 'Лук', icon: 'Sprout', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Mixed_onions.jpg/500px-Mixed_onions.jpg' },
  { eesti: 'Küüslauk', english: 'Garlic', vene: 'Чеснок', icon: 'Sprout', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Garlic_Press_and_Garlic.jpg/640px-Garlic_Press_and_Garlic.jpg' },
  { eesti: 'Paprika', english: 'Bell Pepper', vene: 'Перец', icon: 'BellPepper', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Green-Yellow-Red-Pepper-2009.jpg/500px-Green-Yellow-Red-Pepper-2009.jpg' },
  { eesti: 'Baklažaan', english: 'Eggplant', vene: 'Баклажан', icon: 'Leaf', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/500px-Solanum_melongena_24_08_2012_%281%29.JPG' },
];

export type CategoryType = 'colors' | 'iphone' | 'animals' | 'fruits' | 'vegetables';

export const CATEGORIES: Record<CategoryType, ItemInfo[]> = {
  colors: COLORS,
  iphone: IPHONE_COLORS,
  animals: ANIMALS,
  fruits: FRUITS,
  vegetables: VEGETABLES,
};

export const UI_STRINGS = {
  est: {
    title: 'Eesti Trips-Traps-Trull',
    subtitle: 'Õpi eesti keelt mängides',
    player: 'Mängija',
    you: 'SINA',
    bot: 'BOT',
    friend: 'SÕBER',
    winner: 'Võitja on',
    draw: 'Viik!',
    playAgain: 'Uus mäng',
    howToPlay: 'Kuidas mängida?',
    onlineRoom: 'Online tuba',
    copyLink: 'Kopeeri link',
    copied: 'Kopeeritud',
    waiting: 'Oota vastast...',
    inputPlaceholder: 'Kirjuta siia...',
    helpText: 'Kirjuta sõna ja suund (nt: Punane Keskel)',
    errorFormat: 'Kirjuta sõna ja suund (nt: "Punane Keskel" või "Keskel Punane")',
    errorDirection: 'Tundmatu suund!',
    errorWord: 'Vale sõna! Selles ruudus on:',
    errorTaken: 'See ruut on juba võetud!',
    settings: 'Seaded',
    category: 'Kategooria',
    directions: 'Suunad',
    mode: 'Režiim',
    standard: 'Standard',
    limit3: '3-Limit (Maks 3)',
    online: 'Mängi online',
    resetToDefault: 'Taasta seaded',
    defaultSize: 'Tavasuurus',
    changeOpponent: 'Muuda vastast',
    newGame: 'Uus mäng',
    start: 'Alusta mängu!',
    name: 'Nimi',
    showHints: 'Näita vihjeid',
    difficulty: 'Raskusaste',
    fontSize: 'Teksti suurus',
    standardSize: 'Tavaline X1',
    largeSize: 'Suur X2',
    extraLargeSize: 'Väga suur X3',
    easy: 'Kerge',
    medium: 'Keskmine',
    hard: 'Raske',
    tutorial: {
      step1Title: 'Leia salajane sõna',
      step1Text: 'Igal ruudul on oma nimi (nt "Punane") ja asukoht (nt "Keskel").',
      step2Title: 'Kasuta võlusõnu',
      step2Text: 'Käigu tegemiseks kirjuta mõlemad sõnad eesti keeles. Järjekord pole oluline!',
      step3Title: 'Võida mäng',
      step3Text: 'Saa kolm märki ritta ja oledki võitja!',
      example: 'Punane Keskel'
    },
    directionSetNames: {
      compass: 'Kompass',
      simple: 'Lihtne',
      adventure: 'Seiklus',
      regions: 'Maakonnad',
      family: 'Sugulased',
      solar: 'Päikesesüsteem',
      body: 'Inimkeha',
      weather: 'Ilm',
      emotions: 'Emotsioonid',
      time: 'Aeg',
      elements: 'Elemendid',
      chess: 'Male'
    },
    directionAbbreviations: {
      loe: 'Loe',
      põhi: 'Põhi',
      kirre: 'Kirre',
      lääs: 'Lääs',
      keskel: 'Keskel',
      ida: 'Ida',
      edel: 'Edel',
      lõuna: 'Lõuna',
      kagu: 'Kagu',
      'ülal-vasakul': 'Ülal-Vasakul',
      'ülal': 'Ülal',
      'ülal-paremal': 'Ülal-Paremal',
      'vasakul': 'Vasakul',
      'paremal': 'Paremal',
      'all-vasakul': 'All-Vasakul',
      'all': 'All',
      'all-paremal': 'All-Paremal',
      'loss': 'Loss',
      'mets': 'Mets',
      'järv': 'Järv',
      'koobas': 'Koobas',
      'kodu': 'Kodu',
      'küla': 'Küla',
      'mägi': 'Mägi',
      'põld': 'Põld',
      'jõgi': 'Jõgi',
      'harjumaa': 'Harju',
      'lääne-virumaa': 'L-Viru',
      'ida-virumaa': 'I-Viru',
      'läänemaa': 'Lääne',
      'järvamaa': 'Järva',
      'tartumaa': 'Tartu',
      'pärnumaa': 'Pärnu',
      'viljandimaa': 'Viljandi',
      'võrumaa': 'Võru',
      'ema': 'Ema',
      'isa': 'Isa',
      'tädi': 'Tädi',
      'vend': 'Vend',
      'mina': 'Mina',
      'õde': 'Õde',
      'poeg': 'Poeg',
      'tütar': 'Tütar',
      'lapselaps': 'Lapselaps',
      'merkuur': 'Merkuur',
      'veenus': 'Veenus',
      'maa': 'Maa',
      'marss': 'Marss',
      'päike': 'Päike',
      'jupiter': 'Jupiter',
      'saturn': 'Saturn',
      'uraan': 'Uraan',
      'neptuun': 'Neptuun',
      'silmad': 'Silmad',
      'pea': 'Pea',
      'kõrvad': 'Kõrvad',
      'vasak-käsi': 'Vasak käsi',
      'süda': 'Süda',
      'parem-käsi': 'Parem käsi',
      'vasak-jalg': 'Vasak jalg',
      'kõht': 'Kõht',
      'parem-jalg': 'Parem jalg',
      'torm': 'Torm',
      'vihm': 'Vihm',
      'lumi': 'Lumi',
      'tuul': 'Tuul',
      'pilv': 'Pilv',
      'udu': 'Udu',
      'vikerkaar': 'Vikerkaar',
      'välk': 'Välk',
      'viha': 'Viha',
      'kurbus': 'Kurbus',
      'hirm': 'Hirm',
      'igavus': 'Igavus',
      'õnn': 'Õnn',
      'põnevus': 'Põnevus',
      'segadus': 'Segadus',
      'rahu': 'Rahu',
      'üllatus': 'Üllatus',
      'minevik': 'Minevik',
      'olevik': 'Olevik',
      'tulevik': 'Tulevik',
      'eile': 'Eile',
      'täna': 'Täna',
      'homme': 'Homme',
      'hommik': 'Hommik',
      'keskpäev': 'Keskpäev',
      'õhtu': 'Õhtu',
      'jää': 'Jää',
      'õhk': 'Õhk',
      'valgus': 'Valgus',
      'vesi': 'Vesi',
      'vaim': 'Vaim',
      'tuli': 'Tuli',
      'metall': 'Metall',
      'puit': 'Puit',
      'vanker': 'Vanker',
      'ratsu': 'Ratsu',
      'oda': 'Oda',
      'lipp': 'Lipp',
      'kuningas': 'Kuningas',
      'ettur': 'Ettur',
      'valge': 'Valge',
      'laud': 'Laud',
      'must': 'Must'
    },
    categoryNames: {
      colors: 'Värvid',
      iphone: 'iPhone',
      animals: 'Loomad',
      fruits: 'Puuviljad',
      vegetables: 'Köögiviljad'
    }
  },
  eng: {
    title: 'Estonian Tic-Tac-Toe',
    subtitle: 'Learn Estonian while playing',
    player: 'Player',
    you: 'YOU',
    bot: 'BOT',
    friend: 'FRIEND',
    winner: 'Winner is',
    draw: 'Draw!',
    playAgain: 'New Game',
    howToPlay: 'How to Play?',
    onlineRoom: 'Online Room',
    copyLink: 'Copy Link',
    copied: 'Copied',
    waiting: 'Waiting for opponent...',
    inputPlaceholder: 'Type here...',
    helpText: 'Type word and direction (e.g., Punane Keskel)',
    errorFormat: 'Type word and direction (e.g., "Punane Keskel" or "Keskel Punane")',
    errorDirection: 'Unknown direction!',
    errorWord: 'Wrong word! In this cell is:',
    errorTaken: 'This cell is already taken!',
    settings: 'Settings',
    category: 'Category',
    directions: 'Directions',
    mode: 'Mode',
    standard: 'Standard',
    limit3: '3-Limit (Max 3)',
    online: 'Play Online',
    resetToDefault: 'Reset to Defaults',
    defaultSize: 'Default Size',
    changeOpponent: 'Change Opponent',
    newGame: 'New Game',
    start: 'Let\'s Play!',
    name: 'Name',
    showHints: 'Show Hints',
    difficulty: 'Difficulty',
    fontSize: 'Text Size',
    standardSize: 'Standard X1',
    largeSize: 'Large X2',
    extraLargeSize: 'Extra Large X3',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    tutorial: {
      step1Title: 'Find the Secret Word',
      step1Text: 'Every square has a name (like "Red") and a place (like "Center").',
      step2Title: 'Use Magic Words',
      step2Text: 'To make a move, type both words in Estonian. The order doesn\'t matter!',
      step3Title: 'Win the Game',
      step3Text: 'Get three marks in a row to become the champion!',
      example: 'Punane Keskel'
    },
    directionSetNames: {
      compass: 'Compass',
      simple: 'Simple',
      adventure: 'Adventure',
      regions: 'Regions',
      family: 'Family',
      solar: 'Solar System',
      body: 'Human Body',
      weather: 'Weather',
      emotions: 'Emotions',
      time: 'Time',
      elements: 'Elements',
      chess: 'Chess'
    },
    directionAbbreviations: {
      loe: 'North-West',
      põhi: 'North',
      kirre: 'North-East',
      lääs: 'West',
      keskel: 'Center',
      ida: 'East',
      edel: 'South-West',
      lõuna: 'South',
      kagu: 'South-East',
      'ülal-vasakul': 'Top-Left',
      'ülal': 'Top',
      'ülal-paremal': 'Top-Right',
      'vasakul': 'Left',
      'paremal': 'Right',
      'all-vasakul': 'Bottom-Left',
      'all': 'Bottom',
      'all-paremal': 'Bottom-Right',
      'loss': 'Castle',
      'mets': 'Forest',
      'järv': 'Lake',
      'koobas': 'Cave',
      'kodu': 'Home',
      'küla': 'Village',
      'mägi': 'Mountain',
      'põld': 'Field',
      'jõgi': 'River',
      'harjumaa': 'Harju',
      'lääne-virumaa': 'W-Viru',
      'ida-virumaa': 'E-Viru',
      'läänemaa': 'Lääne',
      'järvamaa': 'Järva',
      'tartumaa': 'Tartu',
      'pärnumaa': 'Pärnu',
      'viljandimaa': 'Viljandi',
      'võrumaa': 'Võru',
      'ema': 'Mom',
      'isa': 'Dad',
      'tädi': 'Aunt',
      'vend': 'Brother',
      'mina': 'Me',
      'õde': 'Sister',
      'poeg': 'Son',
      'tütar': 'Daughter',
      'lapselaps': 'Grandson',
      'merkuur': 'Mercury',
      'veenus': 'Venus',
      'maa': 'Earth',
      'marss': 'Mars',
      'päike': 'Sun',
      'jupiter': 'Jupiter',
      'saturn': 'Saturn',
      'uraan': 'Uranus',
      'neptuun': 'Neptune',
      'silmad': 'Eyes',
      'pea': 'Head',
      'kõrvad': 'Ears',
      'vasak-käsi': 'Left Hand',
      'süda': 'Heart',
      'parem-käsi': 'Right Hand',
      'vasak-jalg': 'Left Foot',
      'kõht': 'Stomach',
      'parem-jalg': 'Right Foot',
      'torm': 'Storm',
      'vihm': 'Rain',
      'lumi': 'Snow',
      'tuul': 'Wind',
      'pilv': 'Cloud',
      'udu': 'Fog',
      'vikerkaar': 'Rainbow',
      'välk': 'Lightning',
      'viha': 'Anger',
      'kurbus': 'Sadness',
      'hirm': 'Fear',
      'igavus': 'Boredom',
      'õnn': 'Happiness',
      'põnevus': 'Excitement',
      'segadus': 'Confusion',
      'rahu': 'Peace',
      'üllatus': 'Surprise',
      'minevik': 'Past',
      'olevik': 'Present',
      'tulevik': 'Future',
      'eile': 'Yesterday',
      'täna': 'Today',
      'homme': 'Tomorrow',
      'hommik': 'Morning',
      'keskpäev': 'Noon',
      'õhtu': 'Evening',
      'jää': 'Ice',
      'õhk': 'Air',
      'valgus': 'Light',
      'vesi': 'Water',
      'vaim': 'Spirit',
      'tuli': 'Fire',
      'metall': 'Metal',
      'puit': 'Wood',
      'vanker': 'Rook',
      'ratsu': 'Knight',
      'oda': 'Bishop',
      'lipp': 'Queen',
      'kuningas': 'King',
      'ettur': 'Pawn',
      'valge': 'White',
      'laud': 'Board',
      'must': 'Black'
    },
    categoryNames: {
      colors: 'Colors',
      iphone: 'iPhone',
      animals: 'Animals',
      fruits: 'Fruits',
      vegetables: 'Vegetables'
    }
  },
  rus: {
    title: 'Эстонские Крестики-Нолики',
    subtitle: 'Учи эстонский играя',
    player: 'Игрок',
    you: 'ТЫ',
    bot: 'РОБОТ',
    friend: 'ДРУГ',
    winner: 'Победитель:',
    draw: 'Ничья!',
    playAgain: 'Новая игра',
    howToPlay: 'Как играть?',
    onlineRoom: 'Онлайн комната',
    copyLink: 'Копировать ссылку',
    copied: 'Скопировано',
    waiting: 'Ожидание оппонента...',
    inputPlaceholder: 'Пиши здесь...',
    helpText: 'Напиши слово и направление (например: Punane Keskel)',
    errorFormat: 'Напиши слово и направление (например: "Punane Keskel" или "Keskel Punane")',
    errorDirection: 'Неизвестное направление!',
    errorWord: 'Неверно! В клетке:',
    errorTaken: 'Занято!',
    settings: 'Настройки',
    category: 'Категория',
    directions: 'Направления',
    mode: 'Режим',
    standard: 'Стандарт',
    limit3: '3-Лимит (Макс 3)',
    online: 'Играть онлайн',
    resetToDefault: 'Сбросить настройки',
    defaultSize: 'Размер по умолчанию',
    changeOpponent: 'Выбор противника',
    newGame: 'Новая игра',
    start: 'Поехали!',
    name: 'Имя',
    showHints: 'Показывать подсказки',
    difficulty: 'Уровень сложности',
    fontSize: 'Размер текста',
    standardSize: 'Обычный X1',
    largeSize: 'Крупный X2',
    extraLargeSize: 'Огромный X3',
    easy: 'Легко',
    medium: 'Средне',
    hard: 'Сложно',
    tutorial: {
      step1Title: 'Найди секретное слово',
      step1Text: 'У каждой клетки есть своё имя (например, "Punane") и место (например, "Keskel").',
      step2Title: 'Используй магию слов',
      step2Text: 'Чтобы сделать ход, напиши оба слова на эстонском. Порядок не важен!',
      step3Title: 'Выиграй игру',
      step3Text: 'Собери три знака в ряд и стань победителем!',
      example: 'Punane Keskel'
    },
    directionSetNames: {
      compass: 'Компас',
      simple: 'Просто',
      adventure: 'Приключение',
      regions: 'Регионы',
      family: 'Семья',
      solar: 'Солнечная система',
      body: 'Тело человека',
      weather: 'Погода',
      emotions: 'Эмоции',
      time: 'Время',
      elements: 'Элементы',
      chess: 'Шахматы'
    },
    directionAbbreviations: {
      loe: 'Сев-Зап',
      põhi: 'Север',
      kirre: 'Сев-Вост',
      lääs: 'Запад',
      keskel: 'Центр',
      ida: 'Восток',
      edel: 'Юго-Зап',
      lõuna: 'Юг',
      kagu: 'Юго-Вост',
      'ülal-vasakul': 'Сверху-Слева',
      'ülal': 'Сверху',
      'ülal-paremal': 'Сверху-Справа',
      'vasakul': 'Слева',
      'paremal': 'Справа',
      'all-vasakul': 'Снизу-Слева',
      'all': 'Снизу',
      'all-paremal': 'Снизу-Справа',
      'loss': 'Замок',
      'mets': 'Лес',
      'järv': 'Озеро',
      'koobas': 'Пещера',
      'kodu': 'Дом',
      'küla': 'Деревня',
      'mägi': 'Гора',
      'põld': 'Поле',
      'jõgi': 'Река',
      'harjumaa': 'Харью',
      'lääne-virumaa': 'Л-Виру',
      'ida-virumaa': 'И-Виру',
      'läänemaa': 'Ляэне',
      'järvamaa': 'Ярва',
      'tartumaa': 'Тарту',
      'pärnumaa': 'Пярну',
      'viljandimaa': 'Вильянди',
      'võrumaa': 'Выру',
      'ema': 'Мама',
      'isa': 'Папа',
      'tädi': 'Тетя',
      'vend': 'Брат',
      'mina': 'Я',
      'õde': 'Сестра',
      'poeg': 'Сын',
      'tütar': 'Дочь',
      'lapselaps': 'Внук',
      'merkuur': 'Меркурий',
      'veenus': 'Венера',
      'maa': 'Земля',
      'marss': 'Марс',
      'päike': 'Солнце',
      'jupiter': 'Юпитер',
      'saturn': 'Сатурн',
      'uraan': 'Уран',
      'neptuun': 'Нептун',
      'silmad': 'Глаза',
      'pea': 'Голова',
      'kõrvad': 'Уши',
      'vasak-käsi': 'Левая рука',
      'süda': 'Сердце',
      'parem-käsi': 'Правая рука',
      'vasak-jalg': 'Левая нога',
      'kõht': 'Живот',
      'parem-jalg': 'Правая нога',
      'torm': 'Шторм',
      'vihm': 'Дождь',
      'lumi': 'Снег',
      'tuul': 'Ветер',
      'pilv': 'Облако',
      'udu': 'Туман',
      'vikerkaar': 'Радуга',
      'välk': 'Молния',
      'viha': 'Гнев',
      'kurbus': 'Грусть',
      'hirm': 'Страх',
      'igavus': 'Скука',
      'õnn': 'Счастье',
      'põnevus': 'Азарт',
      'segadus': 'Смущение',
      'rahu': 'Покой',
      'üllatus': 'Сюрприз',
      'minevik': 'Прошлое',
      'olevik': 'Настоящее',
      'tulevik': 'Будущее',
      'eile': 'Вчера',
      'täna': 'Сегодня',
      'homme': 'Завтра',
      'hommik': 'Утро',
      'keskpäev': 'Полдень',
      'õhtu': 'Вечер',
      'jää': 'Лед',
      'õhk': 'Воздух',
      'valgus': 'Свет',
      'vesi': 'Вода',
      'vaim': 'Дух',
      'tuli': 'Огонь',
      'metall': 'Металл',
      'puit': 'Дерево',
      'vanker': 'Ладья',
      'ratsu': 'Конь',
      'oda': 'Слон',
      'lipp': 'Ферзь',
      'kuningas': 'Король',
      'ettur': 'Пешка',
      'valge': 'Белые',
      'laud': 'Доска',
      'must': 'Черные'
    },
    categoryNames: {
      colors: 'Цвета',
      iphone: 'iPhone',
      animals: 'Животные',
      fruits: 'Фрукты',
      vegetables: 'Овощи'
    }
  }
};

export const CREDENTIALS = [
  { name: 'TikTok', url: 'https://www.tiktok.com/@erikegliens' },
  { name: 'Telegram', url: 'https://t.me/erikegliens' },
  { name: 'GitHub', url: 'https://github.com/ErikEgl/' },
];

export const LOGO_URL = 'https://picsum.photos/seed/estonia-logo/200/200';
